# Generated by Django 4.1.4 on 2022-12-18 12:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=8)),
            ],
        ),
    ]
